// SPDX-FileCopyrightText: 2025 Upbound Inc. <https://upbound.io>
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by angryjet. DO NOT EDIT.
// Code transformed by upjet. DO NOT EDIT.

package v1beta1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	xpresource "github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	resource "github.com/crossplane/upjet/pkg/resource"
	resource1 "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	apisresolver "github.com/upbound/provider-gcp-beta/internal/apis"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

func (mg *EndpointIAMMember) ResolveReferences( // ResolveReferences of this EndpointIAMMember.
	ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("vertexai.gcp-beta.upbound.io", "v1beta1", "Endpoint", "EndpointList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Endpoint),
			Extract:      resource.ExtractParamPath("id", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.EndpointRef,
			Selector:     mg.Spec.ForProvider.EndpointSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Endpoint")
	}
	mg.Spec.ForProvider.Endpoint = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.EndpointRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("vertexai.gcp-beta.upbound.io", "v1beta1", "Endpoint", "EndpointList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Endpoint),
			Extract:      resource.ExtractParamPath("id", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.EndpointRef,
			Selector:     mg.Spec.InitProvider.EndpointSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Endpoint")
	}
	mg.Spec.InitProvider.Endpoint = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.EndpointRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this FeaturestoreEntitytype.
func (mg *FeaturestoreEntitytype) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("vertexai.gcp-beta.upbound.io", "v1beta1", "Featurestore", "FeaturestoreList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Featurestore),
			Extract:      resource1.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.FeaturestoreRef,
			Selector:     mg.Spec.ForProvider.FeaturestoreSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Featurestore")
	}
	mg.Spec.ForProvider.Featurestore = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.FeaturestoreRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("vertexai.gcp-beta.upbound.io", "v1beta1", "Featurestore", "FeaturestoreList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Featurestore),
			Extract:      resource1.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.FeaturestoreRef,
			Selector:     mg.Spec.InitProvider.FeaturestoreSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Featurestore")
	}
	mg.Spec.InitProvider.Featurestore = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.FeaturestoreRef = rsp.ResolvedReference

	return nil
}
