// SPDX-FileCopyrightText: 2025 Upbound Inc. <https://upbound.io>
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by angryjet. DO NOT EDIT.

package v1beta1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this FeaturestoreEntitytype.
func (mg *FeaturestoreEntitytype) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Featurestore),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.FeaturestoreRef,
		Selector:     mg.Spec.ForProvider.FeaturestoreSelector,
		To: reference.To{
			List:    &FeaturestoreList{},
			Managed: &Featurestore{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Featurestore")
	}
	mg.Spec.ForProvider.Featurestore = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.FeaturestoreRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Featurestore),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.FeaturestoreRef,
		Selector:     mg.Spec.InitProvider.FeaturestoreSelector,
		To: reference.To{
			List:    &FeaturestoreList{},
			Managed: &Featurestore{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Featurestore")
	}
	mg.Spec.InitProvider.Featurestore = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.FeaturestoreRef = rsp.ResolvedReference

	return nil
}
