// SPDX-FileCopyrightText: 2025 Upbound Inc. <https://upbound.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

// Hub marks this type as a conversion hub.
func (tr *Dataset) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Endpoint) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EndpointIAMMember) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Featurestore) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *FeaturestoreEntitytype) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Tensorboard) Hub() {}
